// This file is generated by `tools/gen-case-map.rb`. DO NOT EDIT!

size_t shift_jis_get_case_fold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags,
    uint32_t code,
    uint32_t* folded_codes
) {
  if (code < 0x80) {
    return nk_enc_ascii_get_case_fold(enc, flags, code, folded_codes);
  }
  if (code >= 0x8260 && code <= 0x8279) {
    if (folded_codes != NULL) {
      folded_codes[0] = (uint32_t)(code + 33);
    }
    return 1;
  }
  if (code >= 0x839F && code <= 0x83B6) {
    if (folded_codes != NULL) {
      folded_codes[0] = (uint32_t)(code + 32);
    }
    return 1;
  }
  if (code >= 0x8440 && code <= 0x844E) {
    if (folded_codes != NULL) {
      folded_codes[0] = (uint32_t)(code + 48);
    }
    return 1;
  }
  if (code >= 0x844F && code <= 0x8460) {
    if (folded_codes != NULL) {
      folded_codes[0] = (uint32_t)(code + 49);
    }
    return 1;
  }
  if (folded_codes != NULL) {
    folded_codes[0] = code;
  }
  return 1;
}

size_t shift_jis_expand_case_unfold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags,
    const uint32_t* folded_codes,
    size_t folded_codes_len ARG_UNUSED,
    nk_unfold_item_t* unfold_items
) {
  size_t unfold_count = nk_enc_ascii_expand_case_unfold(enc, flags, folded_codes, folded_codes_len, unfold_items);
  uint32_t code = folded_codes[0];
  if (code >= 0x8281 && code <= 0x829A) {
    unfold_items[unfold_count].folded_codes_len = 1;
    unfold_items[unfold_count].unfolded_code = (uint32_t)(code - 33);
    unfold_count++;
  }
  if (code >= 0x83BF && code <= 0x83D6) {
    unfold_items[unfold_count].folded_codes_len = 1;
    unfold_items[unfold_count].unfolded_code = (uint32_t)(code - 32);
    unfold_count++;
  }
  if (code >= 0x8470 && code <= 0x847E) {
    unfold_items[unfold_count].folded_codes_len = 1;
    unfold_items[unfold_count].unfolded_code = (uint32_t)(code - 48);
    unfold_count++;
  }
  if (code >= 0x8480 && code <= 0x8491) {
    unfold_items[unfold_count].folded_codes_len = 1;
    unfold_items[unfold_count].unfolded_code = (uint32_t)(code - 49);
    unfold_count++;
  }
  return unfold_count;
}

nk_error_t shift_jis_iterate_case_fold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags,
    nk_case_fold_callback_t callback,
    void* user_data
) {
  nk_error_t err = nk_enc_ascii_iterate_case_fold(enc, flags, callback, user_data);
  if (err < 0) {
    return err;
  }
  for (uint32_t code = 0x8260; code <= 0x8279; code++) {
    uint32_t folded_code = (uint32_t)(code + 33);
    nk_error_t err = callback(code, &folded_code, 1, user_data);
    if (err < 0) {
      return err;
    }
  }
  for (uint32_t code = 0x839F; code <= 0x83B6; code++) {
    uint32_t folded_code = (uint32_t)(code + 32);
    nk_error_t err = callback(code, &folded_code, 1, user_data);
    if (err < 0) {
      return err;
    }
  }
  for (uint32_t code = 0x8440; code <= 0x844E; code++) {
    uint32_t folded_code = (uint32_t)(code + 48);
    nk_error_t err = callback(code, &folded_code, 1, user_data);
    if (err < 0) {
      return err;
    }
  }
  for (uint32_t code = 0x844F; code <= 0x8460; code++) {
    uint32_t folded_code = (uint32_t)(code + 49);
    nk_error_t err = callback(code, &folded_code, 1, user_data);
    if (err < 0) {
      return err;
    }
  }
  return 0;
}
