// This file is generated by `tools/gen-case-map.rb`. DO NOT EDIT!

static const uint8_t iso_8859_1_fold_map[128] = {
//  "\u0080", "\u0081", "\u0082", "\u0083", "\u0084", "\u0085", "\u0086", "\u0087",
        0x80,     0x81,     0x82,     0x83,     0x84,     0x85,     0x86,     0x87,
//  "\u0088", "\u0089", "\u008A", "\u008B", "\u008C", "\u008D", "\u008E", "\u008F",
        0x88,     0x89,     0x8A,     0x8B,     0x8C,     0x8D,     0x8E,     0x8F,
//  "\u0090", "\u0091", "\u0092", "\u0093", "\u0094", "\u0095", "\u0096", "\u0097",
        0x90,     0x91,     0x92,     0x93,     0x94,     0x95,     0x96,     0x97,
//  "\u0098", "\u0099", "\u009A", "\u009B", "\u009C", "\u009D", "\u009E", "\u009F",
        0x98,     0x99,     0x9A,     0x9B,     0x9C,     0x9D,     0x9E,     0x9F,
//       " ",      "¡",      "¢",      "£",      "¤",      "¥",      "¦",      "§",
        0xA0,     0xA1,     0xA2,     0xA3,     0xA4,     0xA5,     0xA6,     0xA7,
//       "¨",      "©",      "ª",      "«",      "¬",      "­",      "®",      "¯",
        0xA8,     0xA9,     0xAA,     0xAB,     0xAC,     0xAD,     0xAE,     0xAF,
//       "°",      "±",      "²",      "³",      "´",      "µ",      "¶",      "·",
        0xB0,     0xB1,     0xB2,     0xB3,     0xB4,     0xB5,     0xB6,     0xB7,
//       "¸",      "¹",      "º",      "»",      "¼",      "½",      "¾",      "¿",
        0xB8,     0xB9,     0xBA,     0xBB,     0xBC,     0xBD,     0xBE,     0xBF,
//       "À",      "Á",      "Â",      "Ã",      "Ä",      "Å",      "Æ",      "Ç",
        0xE0,     0xE1,     0xE2,     0xE3,     0xE4,     0xE5,     0xE6,     0xE7,
//       "È",      "É",      "Ê",      "Ë",      "Ì",      "Í",      "Î",      "Ï",
        0xE8,     0xE9,     0xEA,     0xEB,     0xEC,     0xED,     0xEE,     0xEF,
//       "Ð",      "Ñ",      "Ò",      "Ó",      "Ô",      "Õ",      "Ö",      "×",
        0xF0,     0xF1,     0xF2,     0xF3,     0xF4,     0xF5,     0xF6,     0xD7,
//       "Ø",      "Ù",      "Ú",      "Û",      "Ü",      "Ý",      "Þ",      "ß",
        0xF8,     0xF9,     0xFA,     0xFB,     0xFC,     0xFD,     0xFE,     0xDF,
//       "à",      "á",      "â",      "ã",      "ä",      "å",      "æ",      "ç",
        0xE0,     0xE1,     0xE2,     0xE3,     0xE4,     0xE5,     0xE6,     0xE7,
//       "è",      "é",      "ê",      "ë",      "ì",      "í",      "î",      "ï",
        0xE8,     0xE9,     0xEA,     0xEB,     0xEC,     0xED,     0xEE,     0xEF,
//       "ð",      "ñ",      "ò",      "ó",      "ô",      "õ",      "ö",      "÷",
        0xF0,     0xF1,     0xF2,     0xF3,     0xF4,     0xF5,     0xF6,     0xF7,
//       "ø",      "ù",      "ú",      "û",      "ü",      "ý",      "þ",      "ÿ",
        0xF8,     0xF9,     0xFA,     0xFB,     0xFC,     0xFD,     0xFE,     0xFF,
};

size_t iso_8859_1_get_case_fold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags,
    uint32_t code,
    uint32_t* folded_codes
) {
  if (code < 0x80) {
    return nk_enc_ascii_get_case_fold(enc, flags, code, folded_codes);
  }
  if (code == 0xDF && (flags & NK_FOLD_FULL) != 0) { // LATIN SMALL LETTER SHARP S
    if (folded_codes != NULL) {
      folded_codes[0] = 0x73;
      folded_codes[1] = 0x73;
    }
    return 2;
  }
  if (folded_codes != NULL) {
    folded_codes[0] = iso_8859_1_fold_map[code - 0x80];
  }
  return 1;
}

size_t iso_8859_1_expand_case_unfold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags,
    const uint32_t* folded_codes,
    size_t folded_codes_len ARG_UNUSED,
    nk_unfold_item_t* unfold_items
) {
  size_t unfold_count = nk_enc_ascii_expand_case_unfold(enc, flags, folded_codes, folded_codes_len, unfold_items);
  uint32_t code = folded_codes[0];
  if ((code >= 0xE0 && code <= 0xF6) || (code >= 0xF8 && code <= 0xFE)) {
    unfold_items[unfold_count].folded_codes_len = 1;
    unfold_items[unfold_count].unfolded_code = (uint32_t)(code - 32);
    unfold_count++;
  }
  if ((flags & NK_FOLD_FULL) != 0 && code == 0x73 && folded_codes_len >= 2 && folded_codes[1] == 0x73) { // "ss"
    unfold_items[unfold_count].folded_codes_len = 2;
    unfold_items[unfold_count].unfolded_code = 0xDF;
    unfold_count++;
  }
  return unfold_count;
}

nk_error_t iso_8859_1_iterate_case_fold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags,
    nk_case_fold_callback_t callback,
    void* user_data
) {
  nk_error_t err = nk_enc_ascii_iterate_case_fold(enc, flags, callback, user_data);
  if (err < 0) {
    return err;
  }
  for (uint32_t code = 0xC0; code <= 0xD6; code++) {
    uint32_t folded_code = (uint32_t)(code + 32);
    nk_error_t err = callback(code, &folded_code, 1, user_data);
    if (err < 0) {
      return err;
    }
  }
  for (uint32_t code = 0xD8; code <= 0xDE; code++) {
    uint32_t folded_code = (uint32_t)(code + 32);
    nk_error_t err = callback(code, &folded_code, 1, user_data);
    if (err < 0) {
      return err;
    }
  }
  if ((flags & NK_FOLD_FULL) != 0) {
    uint32_t folded_codes[2] = {0x73, 0x73}; // "ss"
    nk_error_t err = callback(0xDF, folded_codes, 2, user_data); // LATIN SMALL LETTER SHARP S
    if (err < 0) {
      return err;
    }
  }
  return 0;
}
