// This file is generated by `tools/gen-ctype-range.rb`. DO NOT EDIT!

static uint16_t iso_8859_1_ctype_bits[128] = {
//  "\u0080", "\u0081", "\u0082", "\u0083", "\u0084", "\u0085", "\u0086", "\u0087",
      0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0208,   0x0008,   0x0008,
//  "\u0088", "\u0089", "\u008A", "\u008B", "\u008C", "\u008D", "\u008E", "\u008F",
      0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,
//  "\u0090", "\u0091", "\u0092", "\u0093", "\u0094", "\u0095", "\u0096", "\u0097",
      0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,
//  "\u0098", "\u0099", "\u009A", "\u009B", "\u009C", "\u009D", "\u009E", "\u009F",
      0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,   0x0008,
//       " ",      "¡",      "¢",      "£",      "¤",      "¥",      "¦",      "§",
      0x0284,   0x81A0,   0x00A0,   0x00A0,   0x00A0,   0x00A0,   0x00A0,   0x81A0,
//       "¨",      "©",      "ª",      "«",      "¬",      "­",      "®",      "¯",
      0x00A0,   0x00A0,   0x30E2,   0x81A0,   0x00A0,   0x00A0,   0x00A0,   0x00A0,
//       "°",      "±",      "²",      "³",      "´",      "µ",      "¶",      "·",
      0x00A0,   0x00A0,   0x00A0,   0x00A0,   0x00A0,   0x30E2,   0x81A0,   0x81A0,
//       "¸",      "¹",      "º",      "»",      "¼",      "½",      "¾",      "¿",
      0x00A0,   0x00A0,   0x30E2,   0x81A0,   0x00A0,   0x00A0,   0x00A0,   0x81A0,
//       "À",      "Á",      "Â",      "Ã",      "Ä",      "Å",      "Æ",      "Ç",
      0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,
//       "È",      "É",      "Ê",      "Ë",      "Ì",      "Í",      "Î",      "Ï",
      0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,
//       "Ð",      "Ñ",      "Ò",      "Ó",      "Ô",      "Õ",      "Ö",      "×",
      0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x00A0,
//       "Ø",      "Ù",      "Ú",      "Û",      "Ü",      "Ý",      "Þ",      "ß",
      0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x34A2,   0x30E2,
//       "à",      "á",      "â",      "ã",      "ä",      "å",      "æ",      "ç",
      0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,
//       "è",      "é",      "ê",      "ë",      "ì",      "í",      "î",      "ï",
      0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,
//       "ð",      "ñ",      "ò",      "ó",      "ô",      "õ",      "ö",      "÷",
      0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x00A0,
//       "ø",      "ù",      "ú",      "û",      "ü",      "ý",      "þ",      "ÿ",
      0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,   0x30E2,
};

bool iso_8859_1_code_is_ctype(
    const nk_encoding_t* enc ARG_UNUSED,
    uint32_t code,
    uint32_t ctype
) {
  if (code < 0x80) {
    return nk_enc_ascii_code_is_ctype(enc, code, ctype);
  } else if (ctype < 16) {
    return iso_8859_1_ctype_bits[code - 0x80] & (1 << ctype);
  }
  switch (ctype) {
  case NK_CTYPE_ANY:
    return code <= 0xFF;
  case NK_CTYPE_ASSIGNED:
    if (code >= 0x0 && code <= 0xFF) return true;
    break;
  case NK_CTYPE_SCRIPT_COMMON:
    if (code >= 0x0 && code <= 0x40) return true;
    if (code >= 0x5B && code <= 0x60) return true;
    if (code >= 0x7B && code <= 0xA9) return true;
    if (code >= 0xAB && code <= 0xB9) return true;
    if (code >= 0xBB && code <= 0xBF) return true;
    if (code == 0xD7) return true;
    if (code == 0xF7) return true;
    break;
  case NK_CTYPE_SCRIPT_LATIN:
    if (code >= 0x41 && code <= 0x5A) return true;
    if (code >= 0x61 && code <= 0x7A) return true;
    if (code == 0xAA) return true;
    if (code == 0xBA) return true;
    if (code >= 0xC0 && code <= 0xD6) return true;
    if (code >= 0xD8 && code <= 0xF6) return true;
    if (code >= 0xF8 && code <= 0xFF) return true;
    break;
  }
  return false;
}
