AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 4.0
  NewCops: enable
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'build_config.rb'
    - 'ruby-prototype/**/*'
    - 'tools/**/*'
    - 'test/**/*'
    - 'mrbgems/mruby-naraku/mrblib/**/*'
    - 'mrbgems/mruby-naraku/mrbgem.rake'
  Exclude:
    - 'submodules/**/*'
    - 'build/**/*'
    - '.ruby-lsp/**/*'
    - 'ruby-prototype/lib/mruby-scripts/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 220
  Exclude:
    - 'test/**/*'
    - 'ruby-prototype/test/**/*'

Metrics/BlockLength:
  Max: 60

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 500
  Exclude:
    - 'test/**/*'
    - 'ruby-prototype/test/**/*'

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/MethodLength:
  Max: 200

Metrics/ModuleLength:
  Max: 500

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 50

Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'test/encoding/*'

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'test/**/*'
    - 'mrbgems/mruby-naraku/mrblib/**/*'

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
