AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 4.0
  NewCops: enable
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'build_config.rb'
    - 'ruby-prototype/**/*.rb'
  Exclude:
    - 'submodules/**/*'
    - 'build/**/*'
    - '.ruby-lsp/**/*'
    - 'tests/**/*'
    - 'mrbgems/mruby-naraku/mrblib/**/*'
    - 'mrbgems/mruby-naraku/mrbgem.rake'
    - 'ruby-prototype/lib/mruby-scripts/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 240

Metrics/ModuleLength:
  Max: 240

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 16

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
