// This file is generated by `tools/gen-case-map.rb`. DO NOT EDIT!

static const uint8_t ascii_fold_map[128] = {
//  "\x00", "\x01", "\x02", "\x03", "\x04", "\x05", "\x06",   "\a",
      0x00,   0x01,   0x02,   0x03,   0x04,   0x05,   0x06,   0x07,
//    "\b",   "\t",   "\n",   "\v",   "\f",   "\r", "\x0E", "\x0F",
      0x08,   0x09,   0x0A,   0x0B,   0x0C,   0x0D,   0x0E,   0x0F,
//  "\x10", "\x11", "\x12", "\x13", "\x14", "\x15", "\x16", "\x17",
      0x10,   0x11,   0x12,   0x13,   0x14,   0x15,   0x16,   0x17,
//  "\x18", "\x19", "\x1A",   "\e", "\x1C", "\x1D", "\x1E", "\x1F",
      0x18,   0x19,   0x1A,   0x1B,   0x1C,   0x1D,   0x1E,   0x1F,
//     " ",    "!",   "\"",    "#",    "$",    "%",    "&",    "'",
      0x20,   0x21,   0x22,   0x23,   0x24,   0x25,   0x26,   0x27,
//     "(",    ")",    "*",    "+",    ",",    "-",    ".",    "/",
      0x28,   0x29,   0x2A,   0x2B,   0x2C,   0x2D,   0x2E,   0x2F,
//     "0",    "1",    "2",    "3",    "4",    "5",    "6",    "7",
      0x30,   0x31,   0x32,   0x33,   0x34,   0x35,   0x36,   0x37,
//     "8",    "9",    ":",    ";",    "<",    "=",    ">",    "?",
      0x38,   0x39,   0x3A,   0x3B,   0x3C,   0x3D,   0x3E,   0x3F,
//     "@",    "A",    "B",    "C",    "D",    "E",    "F",    "G",
      0x40,   0x61,   0x62,   0x63,   0x64,   0x65,   0x66,   0x67,
//     "H",    "I",    "J",    "K",    "L",    "M",    "N",    "O",
      0x68,   0x69,   0x6A,   0x6B,   0x6C,   0x6D,   0x6E,   0x6F,
//     "P",    "Q",    "R",    "S",    "T",    "U",    "V",    "W",
      0x70,   0x71,   0x72,   0x73,   0x74,   0x75,   0x76,   0x77,
//     "X",    "Y",    "Z",    "[",   "\\",    "]",    "^",    "_",
      0x78,   0x79,   0x7A,   0x5B,   0x5C,   0x5D,   0x5E,   0x5F,
//     "`",    "a",    "b",    "c",    "d",    "e",    "f",    "g",
      0x60,   0x61,   0x62,   0x63,   0x64,   0x65,   0x66,   0x67,
//     "h",    "i",    "j",    "k",    "l",    "m",    "n",    "o",
      0x68,   0x69,   0x6A,   0x6B,   0x6C,   0x6D,   0x6E,   0x6F,
//     "p",    "q",    "r",    "s",    "t",    "u",    "v",    "w",
      0x70,   0x71,   0x72,   0x73,   0x74,   0x75,   0x76,   0x77,
//     "x",    "y",    "z",    "{",    "|",    "}",    "~", "\x7F",
      0x78,   0x79,   0x7A,   0x7B,   0x7C,   0x7D,   0x7E,   0x7F,
};

size_t nk_enc_ascii_get_case_fold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags ARG_UNUSED,
    uint32_t code,
    uint32_t* folded_codes
) {
  if (folded_codes != NULL) {
    folded_codes[0] = ascii_fold_map[code];
  }
  return 1;
}

size_t nk_enc_ascii_expand_case_unfold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags ARG_UNUSED,
    const uint32_t* folded_codes,
    size_t folded_codes_len ARG_UNUSED,
    nk_unfold_item_t* unfold_items
) {
  uint32_t code = folded_codes[0];
  if ((code >= 0x61 && code <= 0x7A)) {
    unfold_items[0].folded_codes_len = 1;
    unfold_items[0].unfolded_code = (uint32_t)(code - 32);
    return 1;
  }
  return 0;
}

nk_error_t nk_enc_ascii_iterate_case_fold(
    const nk_encoding_t* enc ARG_UNUSED,
    nk_fold_flag_t flags ARG_UNUSED,
    nk_case_fold_callback_t callback,
    void* user_data
) {
  for (uint32_t code = 0x41; code <= 0x5A; code++) {
    uint32_t folded_code = (uint32_t)(code + 32);
    nk_error_t err = callback(code, &folded_code, 1, user_data);
    if (err < 0) {
      return err;
    }
  }
  return 0;
}
