// This file is generated by `tools/gen-ctype-range.rb`. DO NOT EDIT!

static uint16_t ascii_ctype_bits[128] = {
//  "\u0000", "\u0001", "\u0002", "\u0003", "\u0004", "\u0005", "\u0006",     "\a",
      0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,
//      "\b",     "\t",     "\n",     "\v",     "\f",     "\r", "\u000E", "\u000F",
      0x4008,   0x420C,   0x4209,   0x4208,   0x4208,   0x4208,   0x4008,   0x4008,
//  "\u0010", "\u0011", "\u0012", "\u0013", "\u0014", "\u0015", "\u0016", "\u0017",
      0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,
//  "\u0018", "\u0019", "\u001A",     "\e", "\u001C", "\u001D", "\u001E", "\u001F",
      0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,   0x4008,
//       " ",      "!",     "\"",      "#",      "$",      "%",      "&",      "'",
      0x4284,   0xC1A0,   0xC1A0,   0xC1A0,   0x41A0,   0xC1A0,   0xC1A0,   0xC1A0,
//       "(",      ")",      "*",      "+",      ",",      "-",      ".",      "/",
      0xC1A0,   0xC1A0,   0xC1A0,   0x41A0,   0xC1A0,   0xC1A0,   0xC1A0,   0xC1A0,
//       "0",      "1",      "2",      "3",      "4",      "5",      "6",      "7",
      0x78B0,   0x78B0,   0x78B0,   0x78B0,   0x78B0,   0x78B0,   0x78B0,   0x78B0,
//       "8",      "9",      ":",      ";",      "<",      "=",      ">",      "?",
      0x78B0,   0x78B0,   0xC1A0,   0xC1A0,   0x41A0,   0x41A0,   0x41A0,   0xC1A0,
//       "@",      "A",      "B",      "C",      "D",      "E",      "F",      "G",
      0xC1A0,   0x7CA2,   0x7CA2,   0x7CA2,   0x7CA2,   0x7CA2,   0x7CA2,   0x74A2,
//       "H",      "I",      "J",      "K",      "L",      "M",      "N",      "O",
      0x74A2,   0x74A2,   0x74A2,   0x74A2,   0x74A2,   0x74A2,   0x74A2,   0x74A2,
//       "P",      "Q",      "R",      "S",      "T",      "U",      "V",      "W",
      0x74A2,   0x74A2,   0x74A2,   0x74A2,   0x74A2,   0x74A2,   0x74A2,   0x74A2,
//       "X",      "Y",      "Z",      "[",     "\\",      "]",      "^",      "_",
      0x74A2,   0x74A2,   0x74A2,   0xC1A0,   0xC1A0,   0xC1A0,   0x41A0,   0xD1A0,
//       "`",      "a",      "b",      "c",      "d",      "e",      "f",      "g",
      0x41A0,   0x78E2,   0x78E2,   0x78E2,   0x78E2,   0x78E2,   0x78E2,   0x70E2,
//       "h",      "i",      "j",      "k",      "l",      "m",      "n",      "o",
      0x70E2,   0x70E2,   0x70E2,   0x70E2,   0x70E2,   0x70E2,   0x70E2,   0x70E2,
//       "p",      "q",      "r",      "s",      "t",      "u",      "v",      "w",
      0x70E2,   0x70E2,   0x70E2,   0x70E2,   0x70E2,   0x70E2,   0x70E2,   0x70E2,
//       "x",      "y",      "z",      "{",      "|",      "}",      "~", "\u007F",
      0x70E2,   0x70E2,   0x70E2,   0xC1A0,   0x41A0,   0xC1A0,   0x41A0,   0x4008,
};

bool nk_enc_ascii_code_is_ctype(
    const nk_encoding_t* enc ARG_UNUSED,
    uint32_t code,
    uint32_t ctype
) {
  if (ctype < 16) {
    return ascii_ctype_bits[code] & (1 << ctype);
  }
  switch (ctype) {
    case NK_CTYPE_ANY:
    case NK_CTYPE_ASSIGNED:
      return code <= 0x7F;
    case NK_CTYPE_SCRIPT_COMMON:
      if (code >= 0x0 && code <= 0x40) return true;
      if (code >= 0x5B && code <= 0x60) return true;
      if (code >= 0x7B && code <= 0x7F) return true;
      break;
    case NK_CTYPE_SCRIPT_LATIN:
      if (code >= 0x41 && code <= 0x5A) return true;
      if (code >= 0x61 && code <= 0x7A) return true;
      break;
  }
  return false;
}
