#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pp'
require 'optparse'

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'naraku_ruby'

postprocess = false
options = {}
parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename($PROGRAM_NAME)} [options] PATTERN"
  opts.on('--postprocess', 'Postprocess the parsed node') { postprocess = true }

  opts.on('-x', '--extended', 'Enable extended mode') { options[:is_extended_mode] = true }
  opts.on('-i', '--ignore-case', 'Enable ignore case mode') { options[:is_ignore_case] = true }
  opts.on('-m', '--dot-allows-newline', 'Let dot match newline') { options[:dot_allows_newline] = true }
  opts.on('--char-class-strict', 'Enable strict char class parsing') { options[:char_class_is_strict] = true }
  opts.on('--char-type-ascii-only', 'Use ASCII-only char type matching') { options[:char_type_is_ascii_only] = true }
  opts.on('--posix-char-class-ascii-only', 'Use ASCII-only POSIX char class matching') do
    options[:posix_char_class_is_ascii_only] = true
  end
  opts.on('--fold-flags FLAGS', 'Comma-separated fold flags (full,ascii_only,turkish_azeri)') do |flags|
    options[:fold_flags] = flags.split(',').map(&:strip).reject(&:empty?).map(&:to_sym)
  end

  opts.on('--range-quantifier-max-repetition N', Integer, 'Set range quantifier max repetition') do |value|
    options[:range_quantifier_max_repetition_limit] = value
  end
  opts.on('--bare-back-ref-max-num N', Integer, 'Set bare back-reference max number') do |value|
    options[:bare_back_ref_max_num_limit] = value
  end
  opts.on('--max-capture-num N', Integer, 'Set max capture number') { |value| options[:max_capture_num_limit] = value }
  opts.on('--back-ref-max-num N', Integer, 'Set back-reference max number') do |value|
    options[:back_ref_max_num_limit] = value
  end
  opts.on('--max-capture-depth N', Integer, 'Set max capture depth') do |value|
    options[:max_capture_depth_limit] = value
  end
  opts.on('--max-parse-depth N', Integer, 'Set max parse depth') { |value| options[:max_parse_depth_limit] = value }
  opts.on('--warning', 'Enable parser warning callback output') { options[:enable_warning] = true }
end
parser.parse!(ARGV)

pattern = ARGV.shift
abort "#{parser}\nPATTERN is required" if pattern.nil?

pp NarakuRuby.parse(pattern, postprocess:, **options)
