# frozen_string_literal: true

require 'optparse'

require_relative './unicode/ctype_catalog'

def gen_header(cat)
  puts "// This file is generated by `tools/gen-ctype-names.rb`. DO NOT EDIT!"

  current_category = nil
  cat.ctypes.each do |ctype|
    if current_category != ctype.category
      current_category = ctype.category
      puts
      puts "// ============================================================================="
      puts "// #{current_category}:"
      puts "// ============================================================================="
      puts
    end
    puts "#define NK_CTYPE_#{ctype.constant_name} #{ctype.id}"
  end

  puts
  puts "// ============================================================================="
  puts "// Constants:"
  puts "// ============================================================================="
  puts
  puts "#define NK_MAX_CTYPE #{cat.ctypes.size - 1}"
  puts "#define NK_MAX_DEFAULT_SUPPORT_CTYPE #{cat.max_default_support_ctype_id}"
end

GPERF_COMMAND = %w[gperf -L ANSI-C -7 -c -j1 -i0 -t -C -P -T -H propname2ctype_hash -Q propname2ctype_pool -N propname2ctype_lookup]

class DebugIO
  def initialize(io, debug:)
    @io = io
    @debug = debug
  end

  def puts(...)
    @io.puts(...)
    $stderr.puts(...) if @debug
  end

  def close_write(...)
    @io.close_write(...)
  end

  def read(...)
    @io.read(...)
  end
end

def gen_source(cat, debug:)
  gperf_code = IO.popen([*GPERF_COMMAND, err: :err], 'w+') do |io|
    io = DebugIO.new(io, debug: debug)

    max_name_bytes = cat.ctypes.flat_map do |ctype|
      ctype.possible_names.map { |name| Unicode::CTypeCatalog.normalize_name(name).length }
    end.max

    io.puts '%{'
    io.puts '// This file is generated by `tools/gen-ctype-names.rb`. DO NOT EDIT!'
    io.puts '#include <string.h>'
    io.puts '#include <naraku_encoding.h>'
    io.puts
    io.puts "#define PROPNAME_MAX_BYTES (#{max_name_bytes})"
    io.puts
    io.puts 'struct propname2ctype_entry {'
    io.puts '    int32_t name;'
    io.puts '    nk_ctype_t ctype;'
    io.puts '};'
    io.puts '%}'
    io.puts 'struct propname2ctype_entry;'
    io.puts '%%'

    cat.ctypes.each do |ctype|
      ctype.possible_names.each do |name|
        io.puts "%-50s NK_CTYPE_%s" % [Unicode::CTypeCatalog.normalize_name(name) + ',', ctype.constant_name]
      end
    end
    io.puts '%%'
    io.close_write

    io.read
  end

  puts gperf_code
    .gsub(%r{/\*FALLTHROUGH\*/}, '__attribute__((fallthrough));')
    .gsub(%r{\{-1\}}, '{-1, 0}')
    .gsub('offsetof', '(int32_t)offsetof')
end

opt = OptionParser.new

header = false
debug = false
opt.on('--header', 'Generate header file content') { header = true }
opt.on('--debug', 'Enable the debug mode') { debug = true }

opt.parse!(ARGV)
version = ARGV[0]
if version.nil?
  puts opt
  exit 1
end

cat = Unicode::CTypeCatalog.new(version)

if header
  gen_header(cat)
  exit 0
end

gen_source(cat, debug:)
