# frozen_string_literal: true

require 'optparse'

require_relative 'unicode/cprop_catalog'

def gen_header(cat)
  puts '// This file is generated by `tools/gen-cprop-names.rb`. DO NOT EDIT!'

  current_category = nil
  cat.cprops.each do |cprop|
    if current_category != cprop.category
      current_category = cprop.category
      puts
      puts '// ============================================================================='
      puts "// #{current_category}:"
      puts '// ============================================================================='
      puts
    end
    puts "#define NK_CPROP_#{cprop.constant_name} #{cprop.id}"
  end

  puts
  puts '// ============================================================================='
  puts '// Constants:'
  puts '// ============================================================================='
  puts
  puts "#define NK_MAX_CPROP #{cat.cprops.size - 1}"
  puts "#define NK_MAX_DEFAULT_SUPPORT_CPROP #{cat.max_default_support_cprop_id}"
end

GPERF_COMMAND = %w[gperf -L ANSI-C -7 -c -j1 -i0 -t -C -P -T -H name2cprop_hash -Q name2cprop_pool -N
                   name2cprop_lookup].freeze

class DebugIO
  def initialize(io, debug:)
    @io = io
    @debug = debug
  end

  def puts(...)
    @io.puts(...)
    warn(...) if @debug
  end

  def close_write(...)
    @io.close_write(...)
  end

  def read(...)
    @io.read(...)
  end
end

def gen_source(cat, debug:)
  gperf_code = IO.popen([*GPERF_COMMAND, { err: :err }], 'w+') do |io|
    io = DebugIO.new(io, debug:)

    max_name_bytes = cat.cprops.flat_map do |cprop|
      cprop.possible_names.map { |name| Unicode::CpropCatalog.normalize_name(name).length }
    end.max

    io.puts '%{'
    io.puts '// This file is generated by `tools/gen-cprop-names.rb`. DO NOT EDIT!'
    io.puts
    io.puts '#include <string.h>'
    io.puts '#include <naraku_encoding.h>'
    io.puts
    io.puts "#define CPROP_NAME_MAX_BYTES (#{max_name_bytes})"
    io.puts
    io.puts 'struct name2cprop_entry {'
    io.puts '    int32_t name;'
    io.puts '    nk_cprop_t cprop;'
    io.puts '};'
    io.puts '%}'
    io.puts 'struct name2cprop_entry;'
    io.puts '%%'

    cat.cprops.each do |cprop|
      cprop.possible_names.each do |name|
        io.puts format('%-50s NK_CPROP_%s', "#{Unicode::CpropCatalog.normalize_name(name)},", cprop.constant_name)
      end
    end
    io.puts '%%'
    io.close_write

    io.read
  end

  puts gperf_code
    .gsub(%r{/\*FALLTHROUGH\*/}, 'NARAKU_FALLTHROUGH;')
    .gsub('{-1}', '{-1, 0}')
    .gsub('offsetof', '(int32_t)offsetof')
    .gsub('register unsigned int hval = len;', 'register unsigned int hval = (unsigned int)len;')
end

opt = OptionParser.new

header = false
debug = false
opt.on('--header', 'Generate header file content') { header = true }
opt.on('--debug', 'Enable the debug mode') { debug = true }

opt.parse!(ARGV)
version = ARGV[0]
if version.nil?
  puts opt
  exit 1
end

cat = Unicode::CpropCatalog.new(version)

if header
  gen_header(cat)
  exit 0
end

gen_source(cat, debug:)
